### ISSUE TITLE
cp: cannot create regular file '/etc/squid3/.': No such file or directory

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/squid3_ynh#2]
Upon attempting to install, the following error appears:
  - (Reading database ... 45%
  - (Reading database ... 50%
  - (Reading database ... 55%
  - (Reading database ... 60%
  - (Reading database ... 65%
  - (Reading database ... 70%
  - (Reading database ... 75%
  - (Reading database ... 80%
  - (Reading database ... 85%
  - (Reading database ... 90%
  - (Reading database ... 95%
  - (Reading database ... 100%
  - (Reading database ... 105584 files and directories currently installed.)
  - 2018-09-27 17:38:06,153: DEBUG - Preparing to unpack .../squid3_3.5.23-5+deb9u1_all.deb ...
  - 2018-09-27 17:38:06,154: DEBUG - Unpacking squid3 (3.5.23-5+deb9u1) ...
  - 2018-09-27 17:38:06,355: DEBUG - Setting up squid3 (3.5.23-5+deb9u1) ...
  - 2018-09-27 17:38:06,656: DEBUG - + [[ -n /tmp/tmp.cEx1XWqqHI ]]
  - 2018-09-27 17:38:06,656: DEBUG - + rm -rf /tmp/tmp.cEx1XWqqHI
  - 2018-09-27 17:38:06,656: DEBUG - + ynh_package_is_installed squid3-ynh-deps
  - 2018-09-27 17:38:06,656: DEBUG - + dpkg-query -W -f '${Status}' squid3-ynh-deps
  - 2018-09-27 17:38:06,656: DEBUG - + grep -c 'ok installed'
  - 2018-09-27 17:38:06,657: DEBUG - + rm /tmp/squid3-ynh-deps.control
  - 2018-09-27 17:38:06,657: DEBUG - + ynh_app_setting_set squid3 apt_dependencies squid3, mailutils
  - 2018-09-27 17:38:06,657: DEBUG - + sudo yunohost app setting squid3 apt_dependencies --value=squid3, --quiet
  - 2018-09-27 17:38:06,962: DEBUG - + ynh_replace_string __PORT__ 3129 ../conf/squid.conf
  - 2018-09-27 17:38:06,962: WARNING - cp: cannot create regular file '/etc/squid3/.': No such file or directory
  - 2018-09-27 17:38:06,962: DEBUG - + local delimit=@
  - 2018-09-27 17:38:06,963: WARNING - !!
  - 2018-09-27 17:38:06,963: DEBUG - + local match_string=__PORT__
  - 2018-09-27 17:38:06,963: WARNING -   squid3's script has encountered an error. Its execution was cancelled.
  - 2018-09-27 17:38:06,963: DEBUG - + local replace_string=3129
  - 2018-09-27 17:38:06,963: WARNING - !!
  - 2018-09-27 17:38:06,963: DEBUG - + local workfile=../conf/squid.conf
  - 2018-09-27 17:38:06,963: WARNING -
  - 2018-09-27 17:38:06,963: DEBUG - + match_string=__PORT__
  - 2018-09-27 17:38:06,963: DEBUG - + replace_string=3129
  - 2018-09-27 17:38:06,964: DEBUG - + sudo sed --in-place s@__PORT__@3129@g ../conf/squid.conf
  - 2018-09-27 17:38:06,964: DEBUG - + cp -f ../conf/squid.conf /etc/squid3/.
  - 2018-09-27 17:38:06,964: DEBUG - + ynh_exit_properly
  - 2018-09-27 17:38:06,964: DEBUG - + local exit_code=1
  - 2018-09-27 17:38:06,964: DEBUG - + '[' 1 -eq 0 ']'
  - 2018-09-27 17:38:06,964: DEBUG - + trap '' EXIT
  - 2018-09-27 17:38:06,964: DEBUG - + set +eu
  - 2018-09-27 17:38:06,964: DEBUG - + echo -e '!!\n  squid3'\''s script has encountered an error. Its execution was cancelled.\n!!'
  - 2018-09-27 17:38:06,964: DEBUG - + type -t ynh_clean_setup
  - 2018-09-27 17:38:06,965: DEBUG - + ynh_clean_setup
  - 2018-09-27 17:38:06,965: DEBUG - + true
  - 2018-09-27 17:38:06,965: DEBUG - + ynh_die
  - 2018-09-27 17:38:06,965: DEBUG - + echo ''
  - 2018-09-27 17:38:06,965: DEBUG - + exit 1

**Comment by csolisr** [comment]
For the record, there is an `/etc/squid` folder (without the 3) created upon installing Squid manually.

**Comment by anmol26s** [comment]
What is the yunohost version and what device you are using?

**Comment by csolisr** [comment]
Currently using an x86 VPS over Debian Jessie, YunoHost 3.2.1

**Comment by csolisr** [comment]
OK, so I softlinked /etc/squid3 to /etc/squid, which lets the instalation continue, but the following error appears:
  - 2018-09-27 17:43:29,330: DEBUG - + ynh_apt --no-remove -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
  - 2018-09-27 17:43:29,330: DEBUG - + DEBIAN_FRONTEND=noninteractive
  - 2018-09-27 17:43:29,330: DEBUG - + sudo apt-get -y --no-remove -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
  - 2018-09-27 17:43:29,531: DEBUG - Reading package lists...
  - 2018-09-27 17:43:29,832: DEBUG - Building dependency tree...
  - 2018-09-27 17:43:29,832: DEBUG - Reading state information...
  - 2018-09-27 17:43:30,033: DEBUG - 0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
  - 2018-09-27 17:43:30,033: DEBUG - + [[ -n /tmp/tmp.eCFwj9TKn4 ]]
  - 2018-09-27 17:43:30,034: DEBUG - + rm -rf /tmp/tmp.eCFwj9TKn4
  - 2018-09-27 17:43:30,034: DEBUG - + ynh_package_is_installed squid3-ynh-deps
  - 2018-09-27 17:43:30,034: DEBUG - + dpkg-query -W -f '${Status}' squid3-ynh-deps
  - 2018-09-27 17:43:30,034: DEBUG - + grep -c 'ok installed'
  - 2018-09-27 17:43:30,035: DEBUG - + rm /tmp/squid3-ynh-deps.control
  - 2018-09-27 17:43:30,035: DEBUG - + ynh_app_setting_set squid3 apt_dependencies squid3, mailutils
  - 2018-09-27 17:43:30,035: DEBUG - + sudo yunohost app setting squid3 apt_dependencies --value=squid3, --quiet
  - 2018-09-27 17:43:30,336: DEBUG - + ynh_replace_string __PORT__ 3129 ../conf/squid.conf
  - 2018-09-27 17:43:30,336: DEBUG - + local delimit=@
  - 2018-09-27 17:43:30,336: DEBUG - + local match_string=__PORT__
  - 2018-09-27 17:43:30,337: DEBUG - + local replace_string=3129
  - 2018-09-27 17:43:30,337: DEBUG - + local workfile=../conf/squid.conf
  - 2018-09-27 17:43:30,337: DEBUG - + match_string=__PORT__
  - 2018-09-27 17:43:30,337: DEBUG - + replace_string=3129
  - 2018-09-27 17:43:30,337: DEBUG - + sudo sed --in-place s@__PORT__@3129@g ../conf/squid.conf
  - 2018-09-27 17:43:30,339: DEBUG - + cp -f ../conf/squid.conf /etc/squid3/.
  - 2018-09-27 17:43:30,339: DEBUG - + ynh_store_file_checksum /etc/squid3/squid.conf
  - 2018-09-27 17:43:30,339: DEBUG - + local checksum_setting_name=checksum__etc_squid3_squid.conf
  - 2018-09-27 17:43:30,339: DEBUG - ++ sudo md5sum /etc/squid3/squid.conf
  - 2018-09-27 17:43:30,339: DEBUG - ++ cut '-d ' -f1
  - 2018-09-27 17:43:30,340: DEBUG - + ynh_app_setting_set squid3 checksum__etc_squid3_squid.conf e82210dcfe42600770841c577d2b687a
  - 2018-09-27 17:43:30,340: DEBUG - + sudo yunohost app setting squid3 checksum__etc_squid3_squid.conf --value=e82210dcfe42600770841c577d2b687a --quiet
  - 2018-09-27 17:43:30,641: DEBUG - + yunohost service add squid3 --log /var/log/squid3/access.log
  - 2018-09-27 17:43:30,942: DEBUG - The service 'squid3' has been added
  - 2018-09-27 17:43:31,043: DEBUG - + service squid3 restart
  - 2018-09-27 17:43:31,043: WARNING - Failed to restart squid3.service: Unit squid3.service not found.
  - 2018-09-27 17:43:31,044: DEBUG - + ynh_exit_properly
  - 2018-09-27 17:43:31,045: WARNING - !!
  - 2018-09-27 17:43:31,045: DEBUG - + local exit_code=5
  - 2018-09-27 17:43:31,045: WARNING -   squid3's script has encountered an error. Its execution was cancelled.
  - 2018-09-27 17:43:31,046: DEBUG - + '[' 5 -eq 0 ']'
  - 2018-09-27 17:43:31,046: WARNING - !!
  - 2018-09-27 17:43:31,046: DEBUG - + trap '' EXIT
  - 2018-09-27 17:43:31,046: WARNING -
  - 2018-09-27 17:43:31,047: DEBUG - + set +eu
  - 2018-09-27 17:43:31,047: DEBUG - + echo -e '!!\n  squid3'\''s script has encountered an error. Its execution was cancelled.\n!!'
  - 2018-09-27 17:43:31,047: DEBUG - + type -t ynh_clean_setup
  - 2018-09-27 17:43:31,047: DEBUG - + ynh_clean_setup
  - 2018-09-27 17:43:31,047: DEBUG - + true
  - 2018-09-27 17:43:31,047: DEBUG - + ynh_die
  - 2018-09-27 17:43:31,047: DEBUG - + echo ''
  - 2018-09-27 17:43:31,048: DEBUG - + exit 1

**Comment by anmol26s** [comment]
Can you install squid 3 manually and see if squid 3 directory /etc/squid3 has config file?

**Comment by csolisr** [comment]
Yes, there is a directory named /etc/squid and a file inside called squid.conf

**Comment by anmol26s** [comment]
The squid3 should have /etc/squid3/ instead of /etc/squid.
Can you tell the output of `uname -a` ?

**Comment by csolisr** [comment]
`Linux azkware.net 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`

**Comment by csolisr** [comment]
My bad, it was actually Debian Stretch we were talking about.

**Comment by csolisr** [comment]
And yes, when installing squid3 specifically, the folder does have a config file.

**Comment by anmol26s** [comment]
This should actually install squid3 on debian stretch. https://github.com/YunoHost-Apps/squid3_ynh/blob/master/scripts/install#L57
Its good that you installed squid3 manually. Can you try installing the package after the manual install to see if the overwrite the squid3 config file.
Otherwise you can purge squid and squid3 and see if the app install the squid3 correctly.

**Comment by csolisr** [comment]
At this moment, the installation does cause `squid3` to be installed, but after that the installation still fails with the error `Failed to restart squid3.service: Unit squid3.service not found.` It's on one of the logs above.

**Comment by anmol26s** [comment]
Can you purge squid3 and reinstall the package and see if the service is set up? I think its happening because of the broken package.

**Comment by csolisr** [comment]
sudo apt-get remove --purge squid squid3 && sudo apt-get autoremove --purge
    sudo yunohost app install squid3
    
    Warning: Failed to restart squid3.service: Unit squid3.service not found.
    Warning: !!
    Warning:   squid3's script has encountered an error. Its execution was cancelled.
    Warning: !!
    Warning:
    Info: The operation 'Install 'squid3' application' has failed ! To get help, please share the full log of this     operation using the command 'yunohost log display 20180927-184259-app_install-squid3 --share'
    Warning: Failed to get status information via dbus for service squid3, systemctl didn't recognize this service ('NoSuchUnit').

**Comment by anmol26s** [comment]
Install squid3 manually and see why the squid3 service is failing. I am not able to reproduce it on my all debian stretch servers.
It would be good to fix this.

**Comment by csolisr** [comment]
We might be getting to something here:

  - (Reading database ... 15%
  - (Reading database ... 20%
  - (Reading database ... 25%
  - (Reading database ... 30%
  - (Reading database ... 35%
  - (Reading database ... 40%
  - (Reading database ... 45%
  - (Reading database ... 50%
  - (Reading database ... 55%
  - (Reading database ... 60%
  - (Reading database ... 65%
  - (Reading database ... 70%
  - (Reading database ... 75%
  - (Reading database ... 80%
  - (Reading database ... 85%
  - (Reading database ... 90%
  - (Reading database ... 95%
  - (Reading database ... 100%
  - (Reading database ... 105585 files and directories currently installed.)
  - 2018-09-27 19:44:39,897: DEBUG - Preparing to unpack .../squid3_3.5.23-5+deb9u1_all.deb ...
  - 2018-09-27 19:44:39,898: DEBUG - Unpacking squid3 (3.5.23-5+deb9u1) ...
  - 2018-09-27 19:44:39,998: DEBUG - Setting up squid3 (3.5.23-5+deb9u1) ...
  - 2018-09-27 19:44:40,403: DEBUG - Job for squid.service failed because the control process exited with error code.
  - 2018-09-27 19:44:40,404: DEBUG - See "systemctl status squid.service" and "journalctl -xe" for details.
  - 2018-09-27 19:44:40,404: DEBUG - invoke-rc.d: initscript squid, action "reload" failed.
  - 2018-09-27 19:44:40,405: DEBUG - dpkg: error processing package squid3 (--configure):
  - 2018-09-27 19:44:40,405: DEBUG -  subprocess installed post-installation script returned error exit status 1
  - 2018-09-27 19:44:40,406: DEBUG - Errors were encountered while processing:
  - 2018-09-27 19:44:40,406: DEBUG -  squid3
  - 2018-09-27 19:44:40,811: DEBUG - + ynh_die 'Unable to install dependencies'
  - 2018-09-27 19:44:40,812: WARNING - E: Sub-process /usr/bin/dpkg returned an error code (1)
  - 2018-09-27 19:44:40,812: DEBUG - + echo 'Unable to install dependencies'
  - 2018-09-27 19:44:40,813: WARNING - Unable to install dependencies
  - 2018-09-27 19:44:40,814: DEBUG - + exit 1
  - 2018-09-27 19:44:40,814: WARNING - !!
  - 2018-09-27 19:44:40,815: DEBUG - + ynh_exit_properly
  - 2018-09-27 19:44:40,816: WARNING -   squid3's script has encountered an error. Its execution was cancelled.
  - 2018-09-27 19:44:40,816: DEBUG - + local exit_code=1
  - 2018-09-27 19:44:40,817: WARNING - !!
  - 2018-09-27 19:44:40,817: DEBUG - + '[' 1 -eq 0 ']'
  - 2018-09-27 19:44:40,818: WARNING -
  - 2018-09-27 19:44:40,818: DEBUG - + trap '' EXIT
  - 2018-09-27 19:44:40,819: DEBUG - + set +eu
  - 2018-09-27 19:44:40,820: DEBUG - + echo -e '!!\n  squid3'\''s script has encountered an error. Its execution was cancelled.\n!!'
  - 2018-09-27 19:44:40,820: DEBUG - + type -t ynh_clean_setup
  - 2018-09-27 19:44:40,821: DEBUG - + ynh_clean_setup
  - 2018-09-27 19:44:40,821: DEBUG - + true
  - 2018-09-27 19:44:40,822: DEBUG - + ynh_die
  - 2018-09-27 19:44:40,823: DEBUG - + echo ''
  - 2018-09-27 19:44:40,823: DEBUG - + exit 1

**Comment by csolisr** [comment]
Sep 27 19:42:34 azkware.net systemd[1]: Reloading LSB: Squid HTTP Proxy version 3.x.
Sep 27 19:42:34 azkware.net squid[11081]: Reloading Squid HTTP Proxy configuration files.
Sep 27 19:42:34 azkware.net squid[11081]: done.
Sep 27 19:42:34 azkware.net systemd[1]: Reloaded LSB: Squid HTTP Proxy version 3.x.
Sep 27 19:44:40 azkware.net systemd[1]: squid.service: Supervising process 10555 which is not our child. We'll most likely not notice when it exits.
Sep 27 19:44:40 azkware.net systemd[1]: Reloading LSB: Squid HTTP Proxy version 3.x.
Sep 27 19:44:40 azkware.net squid[15846]: Unable to open configuration file: /etc/squid/squid.conf: (2) No such file or directory
Sep 27 19:44:40 azkware.net squid[15835]: FATAL: Unable to open configuration file: /etc/squid/squid.conf: (2) No such file or directory ... failed!
Sep 27 19:44:40 azkware.net systemd[1]: squid.service: Control process exited, code=exited status=3
Sep 27 19:44:40 azkware.net systemd[1]: Reload failed for LSB: Squid HTTP Proxy version 3.x.

**Comment by csolisr** [comment]
From what it looks, /etc/squid/squid.conf is being actually deleted at a certain point...

**Comment by anmol26s** [comment]
Ok
Remove softlink to /etc/squid3 and delete it.
Then `$ apt-get purge squid3`
And finally 
`$ yunohost app install --debug https://github.com/YunoHost-Apps/squid3_ynh/tree/only_squid`

**Comment by csolisr** [comment]
After this the installation seems to be successful, with some warnings. However the system seems unable to connect to the proxy, probably because of a corporate firewall blocking it. That's an issue for another ticket though, so for now I'll mark this one as closed.

**Comment by anmol26s** [comment]
You can change the port port if you know which port is open in your corporate firewall. The server should be kept outside the firewall as yunohost has its own firewall for security.
Thanks
